connector:
    name: oro_importexport
    jobs:
        # Order import job
        ebay_order_import:
            title: "Order Import from Ebay via REST API"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    eltrino_ebay.provider.ebay_order_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 100
        ebay_buyer_import:
            title: "Buyer Import from Ebay via REST API"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    eltrino_ebay.provider.ebay_buyer_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    eltrino_ebay.writer.ebay_buyer_writer
                    parameters:
                        batch_size: 100
