parameters:
    # transport
    eltrino_ebay.ebay_rest_transport.class:                              Eltrino\OroCrmEbayBundle\Provider\Transport\EbayRestTransport

    # providers
    eltrino_ebay.provider.ebay_channel_type.class:                       Eltrino\OroCrmEbayBundle\Provider\EbayChannelType

    # forms
    eltrino_ebay.form.type.ebay_rest_transport_setting.class:            Eltrino\OroCrmEbayBundle\Form\Type\EbayRestTransportSettingFormType

    eltrino_ebay.order.factory.class:                                    Eltrino\OroCrmEbayBundle\Model\Order\OrderFactory

    eltrino_ebay.action.factory.class:                                   Eltrino\OroCrmEbayBundle\Provider\Actions\ActionFactory

    eltrino_ebay.order_action.class:                                     Eltrino\OroCrmEbayBundle\Provider\Actions\OrderAction

    eltrino_ebay.check_action.class:                                     Eltrino\OroCrmEbayBundle\Provider\Actions\CheckConnectionAction

    eltrino_ebay.rest_client.class:                                      Eltrino\OroCrmEbayBundle\Ebay\EbayRestClientImpl

    eltrino_ebay.ebay_rest_client.factory_class:                         Eltrino\OroCrmEbayBundle\Ebay\EbayRestClientFactory

    eltrino_ebay.filters.factory_class:                                  Eltrino\OroCrmEbayBundle\Ebay\Filters\FiltersFactory

    eltrino_ebay.navigation.listener_class:                              Eltrino\OroCrmEbayBundle\EventListener\EbayNavigationListener

services:
   # transport
    eltrino_ebay.ebay_rest_transport:
        class: %eltrino_ebay.ebay_rest_transport.class%
        tags:
            - { name: oro_integration.transport, type: ebay_rest, channel_type: ebay}

   # providers
    eltrino_ebay.provider.ebay_channel_type:
        class: %eltrino_ebay.provider.ebay_channel_type.class%
        tags:
            - { name: oro_integration.channel, type: ebay }

    # forms
    eltrino_ebay.form.type.ebay_rest_transport_setting:
        class: %eltrino_ebay.form.type.ebay_rest_transport_setting.class%
        tags:
            - { name: form.type, alias: eltrino_ebay_rest_transport_setting_form_type }

    eltrino_ebay.order_action:
        class: %eltrino_ebay.order_action.class%

    eltrino_ebay.check_action:
        class: %eltrino_ebay.check_action.class%

    eltrino_ebay.order.factory:
        class: %eltrino_ebay.order.factory.class%

    eltrino_ebay.client.factory:
        class: %eltrino_ebay.client.factory.class%

    eltrino_ebay.action.factory:
        class: %eltrino_ebay.action.factory.class%

    eltrino_ebay.rest_client:
        class: %eltrino_ebay.rest_client.class%

    eltrino_ebay.ebay_rest_client.factory:
        class: %eltrino_ebay.ebay_rest_client.factory_class%

    eltrino_ebay.filters.factory:
        class: %eltrino_ebay.filters.factory_class%

    # event listeners
    eltrino_ebay.event_listener.navigation:
        class: %eltrino_ebay.navigation.listener_class%
        arguments:
            - @doctrine.orm.entity_manager
            - @router
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure, priority: -10 }

    eltrino_ebay.event_listener.grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
            - 'channelId'
            - @oro_datagrid.datagrid.request_params
            - false
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.orders-grid, method: onBuildAfter }

    eltrino_ebay.event_listener.order_items_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
            - 'id'
            - @oro_datagrid.datagrid.request_params
            - false
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.ebay-orderitem-grid, method: onBuildAfter }


